#!/usr/bin/env python
# coding: utf-8

# # Canales por genero

# ## Instalar librerias

# In[1]:


pip install awswrangler


# In[2]:


get_ipython().system('pip install odfpy')


# ## Importar librerias

# In[3]:


import numpy as np
from datetime import datetime
from datetime import timedelta
import pandas as pd
import awswrangler as wr


# In[4]:


pd.set_option("display.max_columns",None)


# ## Lectura de la base de datos desde S3

# In[6]:


df = pd.read_csv("s3://data-lake-tp/generotv/202303/genero_tv_202303.csv000.gz", header=None, sep='|')
df


# ## Asignar la primer fila del dataframe como headers

# In[7]:


df.columns = df.iloc[0]
df


# ## Eliminamos las fila 0

# In[8]:


df.drop([ 0 ],axis= 0 ,inplace= True )
df


# ## Definimos la función para agregar el texto

# In[28]:


def texto(df: pd.DataFrame):
    #Le agregamos el campo texto a nuestro dataframe 
    df['texto'] = None
    df['pregunta']= None
    for index, row in df.iterrows():
            genero=row['genero']
            canales=row['canales']
            df.loc[index,'texto']= f"""Dentro de la transmisión de Totalplay encontraras programas del genero {genero},que podras disfrutar en los siguientes canales {canales}"""
            df.loc[index,'Pregunta']= f"""Me gusta {genero}"""
       
    return df


# In[29]:


df1= texto(df)
df1


# In[27]:


df1['texto'][1]


# In[ ]:


chat= 

