#!/usr/bin/env python
# coding: utf-8

# # Navit total de megas y de segundos transcurridos por cuenta en 2022

# # Importar librerias

# In[1]:


pip install awswrangler


# In[2]:


import numpy as np
from datetime import datetime
import awswrangler as wr
import pandas as pd


# ## Conexion a Redshift

# In[3]:


con = wr.redshift.connect("redshift_devsie")


# ## variables

# In[4]:


meses_list=["enero"]
fecha_inicio=[20230101]
fecha_termino=[20230131]
anio=2023


# ## creacion de tablas publicas

# In[ ]:


for mes, fechai, fechat in zip(meses_list, fecha_inicio, fecha_termino):
    import time
    inicio = time.time()
    print(f"Inicio de cración de la tabla: megas_{mes}_{anio}, con fecha de inicio: {fechai} y fecha de termino: {fechat}")
    sql_tabla = f"""CREATE TABLE public.megas_{mes}_{anio} AS(  
                    SELECT cuenta, SUM(bytes_subida) AS sum_bytes_subida, 
                           SUM(bytes_bajada) AS sum_bytes_bajada, 
                           SUM(segundo_transcurrido) AS  sum_segundo_transcurrido, 
                           SUM(bytes_subida)/1000000 AS sum_megas_subida,  SUM(bytes_bajada)/1000000 AS sum_megas_bajada
                    FROM(SELECT cuenta, bytes_subida, bytes_bajada,
                                to_timestamp (begintime, 'YYYYMMDDHH24MISS',true) as begin_completa,
                                to_timestamp (endtime, 'YYYYMMDDHH24MISS',true) as end_completa,
                                DATEDIFF(sec,begin_completa::timestamp,end_completa::timestamp)::float as segundo_transcurrido          
                         FROM data_lake.edr_aaa
                         WHERE info_day BETWEEN {fechai} AND {fechat})
                    GROUP BY cuenta);
                       """



    conn = wr.redshift.connect("redshift_devsie")

    with conn.cursor() as cursor:
        cursor.execute(sql_tabla)
        cursor.execute("commit;")
        #print(cursor.fetchall()) solo para imprimir el resultado
    conn.close()
    print(f"Termino de crearse la tabla: megas_{mes}_{anio}, con fecha de inicio: {fechai} y fecha de termino: {fechat}")
    fin = time.time()
    tiempo=fin-inicio
    print(f"Tiempo de ejecución de la tabla megas_{mes}_{anio}:  {tiempo} ")  
              


# In[ ]:
