#!/usr/bin/env python
# coding: utf-8

# # Acceder al SFTP con la libreria Paramiko

# ## Instalar librerias

# In[1]:


pip install paramiko


# ## Importar librerias

# In[3]:


import paramiko


# ## Conectarse al SFTP y ver que archivos tiene dentro 

# In[4]:


def list_sftp_files(hostname, port, username, password, remote_directory="."):
    try:
        # Create an SSH client
        ssh_client = paramiko.SSHClient()
        ssh_client.set_missing_host_key_policy(paramiko.AutoAddPolicy())

        # Connect to the SFTP server
        ssh_client.connect(hostname, port, username, password)

        # Create an SFTP session
        sftp = ssh_client.open_sftp()

        # Change to the remote directory
        sftp.chdir(remote_directory)

        # Get the list of files in the remote directory
        file_list = sftp.listdir()

        # Close the SFTP session and SSH connection
        sftp.close()
        ssh_client.close()

        return file_list

    except Exception as e:
        print("Error:", e)
        return []

# Replace these with your SFTP server details
hostname = 'sftp.gbqofs.glassboxdigital.io'
port = 22
username = 'totalplay-sftp'
password = '/home/ec2-user/SageMaker/Navit/SFTP/key.txt'
remote_directory = 'import/attributes'  # Change this to the remote directory you want to list

# List files from the SFTP server
files = list_sftp_files(hostname, port, username, password, remote_directory)
print("Files in the remote directory:")
for file in files:
    print(file)
