#!/usr/bin/env python
# coding: utf-8

# In[7]:


import requests
import json


# In[8]:


url='https://pokeapi.co/api/v2/pokemon-form/'
response =requests.get(url)
print(response)


# In[18]:


if response.status_code == 200:
    payload = response.json()
    results = payload.get('results', [])
    
    if results:
        for pokemon in results:
            name = pokemon['name']
            print(name)


# In[17]:


if response.status_code == 200:
    payload = response.json()
    results = payload.get('results', [])
    print(payload)

