#!/usr/bin/env python
# coding: utf-8

# # Programas en canales

# ## Instalar librerias

# In[1]:


pip install awswrangler


# In[2]:


get_ipython().system('pip install odfpy')


# ## Importar librerias

# In[3]:


import numpy as np
from datetime import datetime
from datetime import timedelta
import pandas as pd
import awswrangler as wr


# In[4]:


pd.set_option("display.max_columns",None)


# ## Conexion a Redshift

# In[5]:


#conexiones a redshift
conn = wr.redshift.connect("redshift_devsie") # redshif viejito
conn_aurora = wr.postgresql.connect("cctp_sandbox_aurora_master_instance") # aurora
con_redshift_2 = wr.redshift.connect("redshift_cctp_bi") #nuevo


# ## Lectura de la base que se encuentra en redshift

# In[6]:


sql = """ SELECT nombre_canal,
                 listagg(distinct programa,',') 
                 within group (order by nombre_canal) as programas
          FROM devsie.data_lake.television_live
          WHERE info_day BETWEEN 20230301 AND 20230328
          GROUP BY nombre_canal
      """


# ## Creamos el dataframe df

# In[ ]:


df = wr.redshift.read_sql_query(sql,conn)


# In[ ]:
