#!/usr/bin/env python
# coding: utf-8

# # Resumen de texto de pdf

# ## Instalar librerias

# In[1]:


pip install pymupdf


# In[2]:


pip install fitz


# In[5]:


pip install pdfminer


# In[7]:


pip install pdfminer.six


# In[11]:


pip install textblob 


# ## Importar librerias

# In[12]:


#Librería PDF -> HTML
import ntpath
from pathlib import Path
import fitz
#Librería para Realizar Resumen 
import bs4 as bs  
import urllib.request  
import re
import nltk
import bs4
import urllib.request
import requests
from bs4 import BeautifulSoup
import urllib.request
from inscriptis import get_text
from googletrans import Translator
#Para la version de googletrans es -> pip install googletrans==3.1.0a0
from pdfminer.high_level import extract_text
from nltk import word_tokenize,sent_tokenize
import heapq  
nltk.download('punkt')
nltk.download('stopwords')
#Librería para la polaridad
from textblob import TextBlob
#Librería para leer txt utf-8
import codecs


# ## Pasar el pdf a html

# In[14]:


def PdfToHTML():
    #Insertamos el PDF(1)
    pdf = "polar-bear-IB-spanish.pdf" # ----> Aquí insertas tu PDF (Recuerda que el nombre de tu pdf debe ser igual)
    documento = fitz.open(pdf)
    pagina = documento.loadPage(0)
    doc = fitz.open(pdf)
    salida = open(pdf+".html","wb")
    for pagina in doc:
        texto = pagina.getText("html").encode("utf8")
        salida.write(texto)
        salida.write(b"\n--------------------\n")
    salida.close()
    Resumen()  

def Resumen():
    #Insertamos el PDF(2)
    pdfTohtml = extract_text("polar-bear-IB-spanish.pdf") # ----> Aquí insertas tu PDF (Recuerda que el nombre de tu pdf debe ser igual)
    articulo_texto = pdfTohtml
    articulo_texto = articulo_texto.replace("[ edit ]", "")
    print ("#########################")
    print ("##### R E S U M E N #####")
    print ("#########################")


# In[ ]:
